/* ─── MassIQ Intelligence Engine API Route ────────────────────────────────
   POST /api/engine

   Step 1: Deterministic physiological engine (runEngine)
           → Authoritative macros, diagnosis, trajectory. Never varies.
   Step 2: Claude Haiku writes coaching narrative constrained by Step 1 output
           → whyThisWorks, objective, nutritionKeyChange, primaryAction

   Numbers are NEVER generated by Claude. Claude only writes the words.
────────────────────────────────────────────────────────────────────────── */

import { NextRequest, NextResponse } from 'next/server'
import { runEngine, buildClaudeContext } from '../../../lib/engine'

export const runtime = 'nodejs'

async function verifyAuth(req: NextRequest): Promise<string | null> {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const anonKey     = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!supabaseUrl || !anonKey) return null;
  const authHeader  = req.headers.get('authorization') || '';
  const bearerToken = authHeader.replace(/^Bearer\s+/i, '').trim();
  if (!bearerToken) return null;
  try {
    const res = await fetch(`${supabaseUrl}/auth/v1/user`, {
      headers: { apikey: anonKey, Authorization: `Bearer ${bearerToken}` },
    });
    if (!res.ok) return null;
    const user = await res.json();
    return user?.id ? user.id : null;
  } catch {
    return null;
  }
}

export async function POST(req: NextRequest) {
  // ── Auth gate ────────────────────────────────────────────────────────────
  const userId = await verifyAuth(req);
  if (!userId) {
    const hasToken = !!(req.headers.get('authorization') || '').trim();
    console.warn('[engine] auth:failed', { reason: hasToken ? 'invalid_token' : 'no_token' });
    return NextResponse.json({ error: 'Sign in to continue' }, { status: 401 });
  }
  console.info('[engine] auth:ok', { user_id: userId });
  // ────────────────────────────────────────────────────────────────────────

  let body: any
  try { body = await req.json() } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  if (!body?.profile) {
    return NextResponse.json({ error: 'Missing required field: profile' }, { status: 400 })
  }

  /* ── 1. Deterministic engine — source of truth for all numbers ────────── */
  let output: any
  try {
    output = runEngine(body)
  } catch (err) {
    console.error('[engine] Calculation error:', err)
    return NextResponse.json({ error: 'Engine calculation failed', detail: String(err) }, { status: 500 })
  }

  /* ── 2. Claude Haiku — narrative only, never numbers ─────────────────── */
  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) {
    // Still usable — macro_targets are correct, just no coaching copy
    return NextResponse.json(output)
  }

  const context = buildClaudeContext(output)
  const prompt  = `${context}

You are writing coaching copy for a fitness app. Using ONLY the data above, return ONLY this JSON (no markdown):
{
  "objective": "One sentence: what this person will achieve and how, referencing their exact calorie/protein targets and timeline.",
  "whyThisWorks": "2-3 sentences: explain the specific mechanism — deficit/surplus vs TDEE, protein target relative to lean mass, expected weekly rate of change. Reference actual numbers.",
  "nutritionKeyChange": "One actionable sentence: the single most important nutrition habit to lock in this week given the primary diagnosis.",
  "primaryAction": "One specific action to take today based on the primary diagnosis."
}`

  try {
    const res = await fetch('https://api.anthropic.com/v1/messages', {
      method:  'POST',
      headers: {
        'content-type':      'application/json',
        'x-api-key':         apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model:      'claude-haiku-4-5-20251001',
        max_tokens: 600,
        system:     'You are a precision fitness coach. Return only valid JSON. Reference exact numbers from the context. Never be generic.',
        messages:   [{ role: 'user', content: prompt }],
      }),
    })

    if (res.ok) {
      const data  = await res.json().catch(() => null)
      const text  = data?.content?.find((b: any) => b?.type === 'text')?.text ?? ''
      const match = text.match(/\{[\s\S]*\}/)
      if (match) {
        try {
          const narrative = JSON.parse(match[0])
          return NextResponse.json({ ...output, narrative })
        } catch {
          console.warn('[engine] Claude narrative JSON parse failed')
        }
      }
    } else {
      console.warn('[engine] Claude narrative request failed:', res.status)
    }
  } catch (err) {
    console.error('[engine] Claude narrative generation error:', err)
  }

  // Fallback: return engine output without narrative — numbers still correct
  return NextResponse.json(output)
}
