"use client";

const C = {
  bg:     '#0A0D0A',
  card:   '#111411',
  border: 'rgba(255,255,255,0.07)',
  green:  '#72B895',
  white:  '#F2F7F2',
  muted:  'rgba(242,247,242,0.58)',
  dim:    'rgba(242,247,242,0.28)',
};

const LAST_UPDATED = 'March 2025';

function NavBar() {
  return (
    <nav style={{
      position: 'sticky', top: 0, zIndex: 50,
      background: 'rgba(10,13,10,0.92)',
      backdropFilter: 'blur(20px)',
      WebkitBackdropFilter: 'blur(20px)',
      borderBottom: `1px solid ${C.border}`,
    }}>
      <div style={{
        maxWidth: 860, margin: '0 auto',
        padding: '0 24px', height: 56,
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      }}>
        <a href="/" style={{ fontSize: 14, fontWeight: 800, color: C.green, letterSpacing: '.04em', textDecoration: 'none' }}>
          MASSIQ
        </a>
        <a href="/app" style={{
          fontSize: 13, fontWeight: 600, color: C.muted, textDecoration: 'none',
          padding: '6px 14px', border: `1px solid ${C.border}`, borderRadius: 99,
        }}>
          Open App
        </a>
      </div>
    </nav>
  );
}

interface Section {
  title: string;
  content: (string | string[])[];
}

const sections: Section[] = [
  {
    title: 'Acceptance of Terms',
    content: [
      'By accessing or using MassIQ ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.',
      'We may update these terms at any time. Continued use of the Service after an update constitutes your acceptance of the revised terms.',
    ],
  },
  {
    title: 'Description of Service',
    content: [
      'MassIQ is a body composition analysis application that uses AI to estimate body fat percentage, physique metrics, and personalised training and nutrition recommendations from photos you upload.',
      'The Service is provided for informational and personal fitness tracking purposes only. It is not a medical device and does not provide medical advice, diagnosis, or treatment.',
    ],
  },
  {
    title: 'Eligibility',
    content: [
      'You must be at least 18 years old to use MassIQ. By creating an account, you represent that you meet this requirement. We reserve the right to terminate accounts that violate this requirement.',
    ],
  },
  {
    title: 'Free and Premium Plans',
    content: [
      'MassIQ offers a Free tier and a Premium subscription:',
      [
        'Free: includes a limited number of scans and basic analysis features.',
        'Premium: includes unlimited scans, adaptive macro recommendations, scan-to-scan progress comparison, and goal timeline projections.',
      ],
      'Feature availability is subject to change. We will communicate material changes to paying subscribers before they take effect.',
    ],
  },
  {
    title: 'Payment and Billing',
    content: [
      'Premium subscriptions are billed on a recurring monthly basis via Stripe. By subscribing, you authorise us to charge your payment method each billing cycle.',
      [
        'You may cancel your subscription at any time via the Manage Billing portal within the app.',
        'Cancellation takes effect at the end of the current billing period. No partial refunds are issued for unused time.',
        'If payment fails, your account will be downgraded to Free after a grace period.',
      ],
      'All prices are in USD unless otherwise stated. We reserve the right to change pricing with 30 days notice to active subscribers.',
    ],
  },
  {
    title: 'User Content and Scan Data',
    content: [
      'You retain ownership of all photos and data you upload to MassIQ.',
      'By uploading content, you grant MassIQ a limited, non-exclusive licence to process that content for the sole purpose of providing the Service to you.',
      'You are responsible for ensuring that any photos you upload comply with applicable law and do not contain content that is illegal, harmful, or a violation of third-party rights.',
      'We will not use your content to train AI models or for any purpose beyond delivering the Service.',
    ],
  },
  {
    title: 'AI Analysis Disclaimer',
    content: [
      'All body composition estimates, projections, and recommendations generated by MassIQ are produced by an AI model and are estimates only.',
      [
        'Results are not a substitute for professional medical, nutritional, or fitness advice.',
        'Body fat estimates carry an inherent margin of error. MassIQ does not guarantee accuracy.',
        'Projections (timelines, stage forecasts) are based on statistical averages and may not reflect your individual results.',
        'Always consult a qualified health professional before making significant changes to your diet or exercise programme.',
      ],
    ],
  },
  {
    title: 'Prohibited Uses',
    content: [
      'You agree not to use the Service to:',
      [
        'Upload photos of any person without their explicit consent.',
        'Attempt to reverse engineer, scrape, or extract data from the Service.',
        'Circumvent scan limits or payment requirements through technical means.',
        'Violate any applicable local, national, or international law or regulation.',
        'Upload content that is abusive, threatening, harassing, or otherwise objectionable.',
      ],
    ],
  },
  {
    title: 'Intellectual Property',
    content: [
      'All software, design, copy, analysis logic, and brand assets of MassIQ are the property of the Service operator and are protected by applicable intellectual property law.',
      'Nothing in these terms grants you a licence to copy, reproduce, distribute, or create derivative works from MassIQ content.',
    ],
  },
  {
    title: 'Limitation of Liability',
    content: [
      'To the maximum extent permitted by law, MassIQ and its operators are not liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including reliance on AI-generated analysis.',
      'Our total liability for any claim arising from use of the Service is limited to the amount you paid us in the 30 days preceding the claim.',
    ],
  },
  {
    title: 'Termination',
    content: [
      'We reserve the right to suspend or terminate your account if you violate these terms or engage in conduct we reasonably determine to be harmful to the Service or other users.',
      'You may close your account at any time from the Profile section of the app. Upon closure, your data will be deleted in accordance with our Privacy Policy.',
    ],
  },
  {
    title: 'Governing Law',
    content: [
      'These terms are governed by applicable law. Any disputes shall be resolved in the jurisdiction in which the Service operator is registered.',
    ],
  },
  {
    title: 'Contact',
    content: [
      'For questions about these terms, contact us at: legal@massiq.app',
    ],
  },
];

export default function TermsPage() {
  return (
    <div style={{
      minHeight: '100dvh',
      background: C.bg,
      fontFamily: 'system-ui, -apple-system, "Segoe UI", sans-serif',
      color: C.white,
      WebkitFontSmoothing: 'antialiased',
    }}>
      <NavBar />

      <main style={{ maxWidth: 760, margin: '0 auto', padding: '56px 24px 100px' }}>
        {/* Header */}
        <div style={{ marginBottom: 52 }}>
          <div style={{
            fontSize: 11, fontWeight: 600, color: C.green,
            textTransform: 'uppercase', letterSpacing: '.14em', marginBottom: 14,
          }}>
            Legal
          </div>
          <h1 style={{
            fontSize: 38, fontWeight: 800, color: C.white,
            letterSpacing: '-.03em', lineHeight: 1.1, margin: '0 0 14px',
          }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: 14, color: C.muted, margin: 0 }}>
            Last updated: {LAST_UPDATED}
          </p>
        </div>

        {/* Intro */}
        <div style={{
          background: C.card, border: `1px solid ${C.border}`,
          borderRadius: 16, padding: '22px 24px', marginBottom: 40,
        }}>
          <p style={{ fontSize: 14, color: C.muted, lineHeight: 1.75, margin: 0 }}>
            These terms govern your use of MassIQ. They are written in plain language. If something is unclear, contact us before using the Service.
          </p>
        </div>

        {/* Sections */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
          {sections.map((section, i) => (
            <div
              key={section.title}
              style={{
                paddingTop: 36,
                paddingBottom: 36,
                borderBottom: i < sections.length - 1 ? `1px solid ${C.border}` : 'none',
              }}
            >
              <h2 style={{
                fontSize: 17, fontWeight: 700, color: C.white,
                letterSpacing: '-.015em', margin: '0 0 14px',
              }}>
                {section.title}
              </h2>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                {section.content.map((block, j) => {
                  if (Array.isArray(block)) {
                    return (
                      <ul key={j} style={{ margin: 0, padding: '0 0 0 20px', display: 'flex', flexDirection: 'column', gap: 8 }}>
                        {block.map((item, k) => (
                          <li key={k} style={{ fontSize: 14, color: C.muted, lineHeight: 1.7 }}>
                            {item}
                          </li>
                        ))}
                      </ul>
                    );
                  }
                  return (
                    <p key={j} style={{ fontSize: 14, color: C.muted, lineHeight: 1.75, margin: 0 }}>
                      {block}
                    </p>
                  );
                })}
              </div>
            </div>
          ))}
        </div>

        {/* Footer nav */}
        <div style={{
          marginTop: 56, paddingTop: 32, borderTop: `1px solid ${C.border}`,
          display: 'flex', gap: 20, flexWrap: 'wrap', alignItems: 'center',
        }}>
          <a href="/privacy" style={{ fontSize: 13, color: C.muted, textDecoration: 'underline' }}>
            Privacy Policy
          </a>
          <a href="/app" style={{ fontSize: 13, color: C.muted, textDecoration: 'underline' }}>
            Back to App
          </a>
        </div>
      </main>
    </div>
  );
}
